In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [3]:
type(arr)

numpy.ndarray

In [4]:
mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [5]:
print(type(arr))
print(type(mat))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
arr[1]

20

In [7]:
arr[[0,1,3]]

array([10, 20, 40])

In [8]:
arr[1:4]

array([20, 30, 40])

In [9]:
mat[0,1]

2

In [10]:
r0 = mat[0,:]
r0

array([1, 2, 3, 4])

In [11]:
mat[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
mat[:, 1]

array([ 2,  6, 10, 14])

In [13]:
mat[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [14]:
mat[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [15]:
m1 = np.array([[1, 1], [1, 1]])
m1

array([[1, 1],
       [1, 1]])

In [16]:
m2 = np.array([[2, 2], [2, 2]])
m2

array([[2, 2],
       [2, 2]])

In [17]:
m2 + m1

array([[3, 3],
       [3, 3]])

In [18]:
m2 - m1

array([[1, 1],
       [1, 1]])

In [19]:
10 * m1

array([[10, 10],
       [10, 10]])

In [20]:
m1/2  # 1/2をかけるのと同じ

array([[0.5, 0.5],
       [0.5, 0.5]])

In [21]:
m1*m2

array([[2, 2],
       [2, 2]])

In [22]:
m1@m2

array([[4, 4],
       [4, 4]])

In [23]:
np.dot(m1,m2)

array([[4, 4],
       [4, 4]])

In [24]:
m3 = np.array([[1,2,3],[4,5,6]])
m3

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
m3.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [26]:
m3.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [27]:
from numpy.linalg import inv

m4 = np.array([[1,2],[3,4]])

In [28]:
inv(m4)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [29]:
dir(m3)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [30]:
m3.shape

(2, 3)

In [31]:
r0 = mat[0,:]

In [32]:
type(r0)

numpy.ndarray

In [33]:
r0_list = r0.tolist()

r0_list

[1, 2, 3, 4]

In [34]:
type(r0_list)

list

In [35]:
np.sqrt(4)

2.0

In [36]:
np.exp(10)

22026.465794806718

In [37]:
np.log(10)

2.302585092994046

In [38]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [40]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [41]:
np.arange(5,10,0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [42]:
xx = [1,2,3,4,5,6]
np.mean(xx)

3.5

In [43]:
np.median(xx)

3.5

In [44]:
np.var(xx,ddof=1)

3.5

In [45]:
np.std(xx,ddof=1)

1.8708286933869707

In [46]:
xy = [[1,2,3,4,5,6],[1,6,2,5,3,1]]
np.cov(xy,ddof=1)

array([[ 3.5, -0.6],
       [-0.6,  4.4]])

In [47]:
np.corrcoef(xy)

array([[ 1.        , -0.15289416],
       [-0.15289416,  1.        ]])

In [48]:
list0 = [1.0, 2.0, 3.0, 4.0, 5.0]

In [49]:
list1 = []
for i in list0:
    list1.append(i + 10)

list1

[11.0, 12.0, 13.0, 14.0, 15.0]

In [50]:
list2 = [i + 10 for i in list0]
list2

[11.0, 12.0, 13.0, 14.0, 15.0]

In [51]:
list0 + [10]

[1.0, 2.0, 3.0, 4.0, 5.0, 10]

In [52]:
list0 + 10

TypeError: can only concatenate list (not "int") to list

In [53]:
arr0 = np.array(list0)
arr0

array([1., 2., 3., 4., 5.])

In [54]:
arr0 + 10

array([11., 12., 13., 14., 15.])

In [55]:
arr0 + np.array([10]*5)

array([11., 12., 13., 14., 15.])

In [56]:
arr0 - 5

array([-4., -3., -2., -1.,  0.])

In [57]:
arr0 * 10  

array([10., 20., 30., 40., 50.])

In [58]:
arr0 ** 2

array([ 1.,  4.,  9., 16., 25.])

In [59]:
np.sqrt(arr0)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [60]:
np.log(arr0)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [61]:
y = arr0 * 2 + np.sqrt(arr0) + 10
y

array([13.        , 15.41421356, 17.73205081, 20.        , 22.23606798])

In [62]:
mat0 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat0

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
mat0 * 10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [64]:
np.sqrt(mat0)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [65]:
np.log(mat0)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])