In [1]:
s = "Kobe University"  # globalスコープ

def func_1():
    s = "神戸大学"  # localスコープ
    print(s)

In [2]:
print(s)

Kobe University


In [3]:
func_1()

神戸大学


In [4]:
def func_2():
    a_local = 3
    print(a_local)

func_2()

3


In [5]:
a_local

NameError: name 'a_local' is not defined

In [6]:
a = 10

def func_3(x):
    return a + x

func_3(2)

12

In [7]:
a = 1000

In [8]:
func_3(2)

1002

In [9]:
def func_4(x):
    a = 10
    return a + x

func_4(2)

12

In [10]:
0.3 == 0.1 + 0.1 + 0.1

False

In [11]:
format(0.3, '.55f')

'0.2999999999999999888977697537484345957636833190917968750'

In [12]:
format(0.1, '.55f')

'0.1000000000000000055511151231257827021181583404541015625'

In [13]:
2.0**52

4503599627370496.0

In [14]:
2.0**52 == 2.0**52 + 1

False

In [15]:
2.0**53

9007199254740992.0

In [16]:
2.0**53 == 2.0**53 + 1

True

In [17]:
import numpy as np
np.isclose(0.3, 0.1+0.1+0.1)

True

In [18]:
dir(0.1)

['__abs__',
 '__add__',
 '__bool__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getformat__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__le__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__set_format__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 'as_integer_ratio',
 'conjugate',
 'fromhex',
 'hex',
 'imag',
 'is_integer',
 'real']

In [19]:
(0.1).real

0.1

In [20]:
(0.1).as_integer_ratio()

(3602879701896397, 36028797018963968)

In [21]:
a = 0.1
a.real, a.as_integer_ratio()

(0.1, (3602879701896397, 36028797018963968))

In [22]:
a = 0.1

In [23]:
id(a)

140682603386032

In [24]:
b = a

In [25]:
id(b)

140682603386032

In [26]:
a is b

True

In [27]:
c = 0.1
id(c)

140682603386704

In [28]:
c is a, c == a

(False, True)

In [29]:
d = 1
e = 1
d is e, d == e

(True, True)

In [30]:
def func(x):
    return x**2

func(2)

4

In [31]:
id(func)

140682603618368

In [32]:
f = [1,2,3]
f

[1, 2, 3]

In [33]:
g = f

In [34]:
g is f, id(g), id(f)

(True, 140682603587776, 140682603587776)

In [35]:
f.append(100)
f

[1, 2, 3, 100]

In [36]:
g

[1, 2, 3, 100]

In [37]:
f is g, id(f), id(g)

(True, 140682603587776, 140682603587776)

In [38]:
f_copy = f.copy()
f_copy

[1, 2, 3, 100]

In [39]:
f_copy is f

False

In [40]:
from copy import deepcopy
f_deep = deepcopy(f)
f_deep

[1, 2, 3, 100]

In [41]:
# list()による浅いコピー
ff1 = list(f)
ff1, ff1 is f

([1, 2, 3, 100], False)

In [42]:
# インデクシング
ff2 = f[1]
ff2, ff2 is f

(2, False)

In [43]:
# スライシング
ff3 = f[:]
ff3, ff3 is f

([1, 2, 3, 100], False)

In [44]:
import numpy as np

In [45]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [46]:
arr_slice = arr[1:3]
arr_slice

array([2, 3])

In [47]:
arr_slice[0] = 200
arr_slice

array([200,   3])

In [48]:
arr

array([  1, 200,   3,   4,   5])

In [49]:
arr_copy = arr[1:3].copy()
arr_copy

array([200,   3])

In [50]:
arr_copy[1] = 300
arr_copy

array([200, 300])

In [51]:
arr

array([  1, 200,   3,   4,   5])

In [52]:
import pandas as pd
df = pd.DataFrame({'a':np.arange(4), 'b':np.arange(4)})
df

a  b
0  0  0
1  1  1
2  2  2
3  3  3

In [53]:
df_slice = df.iloc[1:3,:]
df_slice

a  b
1  1  1
2  2  2

In [54]:
df.iloc[1,1] = 100
df

a    b
0  0    0
1  1  100
2  2    2
3  3    3

In [55]:
df_slice

a    b
1  1  100
2  2    2

In [56]:
df_copy = df.copy().iloc[1:3,:]
df_copy

a    b
1  1  100
2  2    2

In [57]:
df.iloc[2,1] = 2000
df

a     b
0  0     0
1  1   100
2  2  2000
3  3     3

In [58]:
df_copy

a    b
1  1  100
2  2    2

In [59]:
df_slice

a     b
1  1   100
2  2  2000